#!/bin/bash

# This script sets the hostname to a pre-defined value including the hardware serial number

PREFIX="its-"
SERIAL=$(cat /proc/cpuinfo | grep Serial | cut -d ' ' -f 2)
DASHED_SERIAL=$(echo "$SERIAL" | sed 's/.\{4\}/&-/g' | sed 's/-$//')
HOSTNAME=$PREFIX$DASHED_SERIAL

OLD_HOSTNAME=`hostname -s`

if [ "$OLD_HOSTNAME" = "$HOSTNAME" ]; then
  echo "Hostname is already current, nothing to change here"
else
  echo "Setting hostname to $HOSTNAME and rebooting system ..."
  hostnamectl --no-ask-password set-hostname $HOSTNAME
  systemctl reboot
fi
